### ISSUE TITLE
VSCODE- Insiders: Timed out waiting for the PowerShell extension to start

### ISSUE THREAD

**Issue by iricigor** [PowerShell/vscode-powershell#1046]
### System Details

- Operating system name and version: Windows 10 
- VS Code version: 1.18.0 Insiders (commit date 2017-10-06T05:26:16.770Z)
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`:  5.1.15063.632

### Issue Description

Error: Timed out waiting for the PowerShell extension to start.

This seems to be specific for latest 1.18 insiders build. All works normally on 1.17 public version.
I tried multiple computers and its the same behaviour.  
PowerShell extension is timing out when pressing F5, or trying to start any script.

![image](https://user-images.githubusercontent.com/15923171/31279340-05e7bb6a-aaa9-11e7-83bc-a01628bccda3.png)

### Steps to reproduce
- On clean Windows 10 machine install VS Code Insiders 1.18.0. 
- Install PowerShell extension v.1.4.3
- Wirite simple script (something as Write-Host 1)
- Press F5

Expected behaviour is to diplay 1 in console. But, nothing actually happens. After some time, time out error will appear.

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1362792/logs.zip)

**Comment by rkeithhill** [comment]
If you set script analysis to false (in your settings):
```
"powershell.scriptAnalysis.enable": false,
```
and reload VSCode Insiders, does it still timeout?

**Comment by iricigor** [comment]
Just tried it, and yes, still the same behavior.

**Comment by kborowinski** [comment]
I have the same behavior in VS Code 1.18.0. The PowerShell extension does not start.

**Comment by iricigor** [comment]
Build from 10-10-2017 has the same issue.

**Comment by jamestupper** [comment]
I'm seeing the same issue.

- Visual Studio Code version: 1.18.0-insider (Date 2017-10-13T08:55:13.465Z)
- PowerShell extension version: v1.4.3

**Comment by DarkLite1** [comment]
Build from 16/10/2017 same issue.

**Comment by iricigor** [comment]
This issue was reported in [VS Code repo also](https://github.com/Microsoft/vscode/issues/36268), but as per explanation there, it is a PowerShell issue: _"VSCode has deprecated some API that Powershell is using. Powershell needs to update to this."_

**Comment by rkeithhill** [comment]
I plan to look into this tonight.

**Comment by rkeithhill** [comment]
Been looking at this for several hours.  In the past, debug protocol changes have been minimal and simple to adapt to.  However, the required changes for this change are bit more extensive than I was hoping they would be.  It's going to take a little while.  I'm hopeful we'll get this implemented before VSCode 1.18 drops.

**Comment by DarkLite1** [comment]
[#36268](https://github.com/Microsoft/vscode/issues/36268)

**Comment by rkeithhill** [comment]
Some progress tonight. Finally got to the point where the PowerShell debugger is started.  No breakpoints are being hit but this is better than last night. :-)

**Comment by DarkLite1** [comment]
Awesome Keith, one step at a time. The most important thing is, it's not broken in the stable version. Only for us, the beta guinea pigs :smiley:

**Comment by rkeithhill** [comment]
Woohoo.  Basic debugging is working.  Now just need to test the various (and numerous) debug configurations.

**Comment by carlocardella** [comment]
Great news, thanks :)

**Comment by rkeithhill** [comment]
PR for the fix has been submitted - pending review.

**Comment by rkeithhill** [comment]
BTW there is still an issue with "Attach to process" debugging.  Separate issue that has me scratching my head.  Might need @daviwil help on that one.

**Comment by kborowinski** [comment]
@rkeithhill @daviwil: I second that. It would be super great if you guys could fix "attach to process" bug. It's really making my d2d work hard.

**Comment by rkeithhill** [comment]
The original issue should be fixed with the 1.5.0 release.  We are tracking the attach to process issue in the PSES repo - https://github.com/PowerShell/PowerShellEditorServices/issues/551

**Comment by kborowinski** [comment]
Unfortunately it looks like the _attach to process_ is still crashing _PowerShellEditorServices_. I get _ProtocolEndpoint_UnhandledException_ in _EditorServicesHost.cs_ with PS 1.5.0 either on VSCode 1.17.2 and latest VSCode 1.18.0 insiders version. Logs attached.

[vsc_1_17_2_ps_1_5_0_logs.zip](https://github.com/PowerShell/vscode-powershell/files/1423999/vsc_1_17_2_ps_1_5_0_logs.zip)
[vsc_1_18_0_ps_1_5_0_logs.zip](https://github.com/PowerShell/vscode-powershell/files/1424000/vsc_1_18_0_ps_1_5_0_logs.zip)

**Comment by gdwnet** [comment]
I get this on the v1.17 release as well, it seems very hit and miss.

**Comment by Bummibaer** [comment]
I'm using V1.19.3 and Windows 7 Professional.
When I run VS as Admin, I get the same error.
It seems, when I resume after some minutes.

**Comment by rkeithhill** [comment]
Can you give this a try and let me know how it goes? https://github.com/PowerShell/vscode-powershell/issues/1048#issuecomment-365837862
