### ISSUE TITLE
Add-AzureRmAccount doesn't work in VS Code

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#155]
The `Add-AzureRmAccount` (with no parameters) command doesn't pop up the expected login dialog, and hangs the Output window.

In the PowerShell ISE, the login dialog appears correctly:

![image](https://cloud.githubusercontent.com/assets/466713/14716973/8bea8bc6-07ac-11e6-9f4a-dfcaac693703.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Strange, I'll take a look.

**Comment by Chrisboh** [comment]
So it looks like if you set a break point to the line that follows then things seem to work.  In my case if I did the following I could get the dialog to pop and everything else worked.  If I don't set the break point then everything seems to hang.

`Login-AzureRmAccount`
`Set-AzureRmContext -SubscriptionId $SubId <- Set break point here`

**Comment by rkeithhill** [comment]
Sounds like a duplicate for issue #149.

**Comment by daviwil** [comment]
Yep, sounds like that issue.  Trying to get 0.6.0 out ASAP.

**Comment by daviwil** [comment]
I've verified that this is now fixed in the upcoming 0.6.0 release.  I'll close this bug as soon as the update has been shipped.

**Comment by legobytes** [comment]
I'm still seeing the issue with Login-AzureRmAccount not prompting for login credentials unless I have a break on the following line. I'm using VSCode 1.4 with PowerShell Extension version 0.6.2 on Windows 10.

**Comment by kilasuit** [comment]
@legobytes - could you raise this as a new issue and reference this one by using the issue number #155
