### ISSUE TITLE
Script fails to run on second run

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#2319]
On request of @TylerLeonhardt in #2175 I am creating this as a separate issue.

## Description
When breakpoints are set in at least two other open files, the current open file (which does not contain a breakpoint) can only be executed once. Upon a second execution `vscode-insders` freezes.

## Steps to reproduce the issue:
1. Create 3 files:
`File1.ps1` contains code with no breakpoint (Ex. `Get-Process`)
`File2.ps1` contains code with a breakpoint (Ex. `Start-Sleep -Seconds 1`, breakpoint line 1)
`File3.ps1` contains code with a breakpoint (Ex. `Start-Sleep -Seconds 1`, breakpoint line 1)
2. When all 3 files are open in the editor pane and `File1.ps1` is focused press `F5`
Notice that `Get-Process` is executed correctly and all processes are retrieved
3. Press `F5` again and notice that `Get-Process` is not executed, an orange bar is displayed at the bottom and the debug panel to stop debugging is floating at the top but doesn't respond to any clicks and stays there.
![image](https://user-images.githubusercontent.com/10828570/69219165-8ee87e00-0b72-11ea-9f69-e6b2ad4486f4.png)

## Workarounds:

- Close and reopen `vscode-insiders` to have one other successful run
- Remove all breakpoints in all other files

## System details
@rjmholt I hope you can simulate this properly now. I'm currently using `PowerShell Preview 2019.11.0` and `vscode-insiders`:
```
Version: 1.41.0-insider (user setup)
Commit: 4934a6f487b9ed6b99b900ae0710c7b452792e20
Date: 2019-11-20T05:25:39.619Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.2.9200
```

**Comment by JamesLear92** [comment]
This was driving me nuts! I didn't get to even run a script once. But after removing all breakpoints on all files debugging actually starts to debug now.
Thanks!

**Comment by SydneyhSmith** [comment]
@DarkLite1 thanks for opening this-- @TylerLeonhardt has a repro and is actively working on this

**Comment by TylerLeonhardt** [comment]
For those of you having the issue, would you mind testing out this version? It should fix the issue.

[PowerShell-insiders.vsix.zip](https://github.com/PowerShell/vscode-powershell/files/3877576/PowerShell-insiders.vsix.zip)

Let me know if you need help installing it.

**Comment by JustinGrote** [comment]
@TylerLeonhardt was just about to open a related issue for pester test debugging. Here's the repro and logs
![Capture](https://user-images.githubusercontent.com/15258962/69442802-10224b00-0d02-11ea-9d37-4399e9cac89e.gif)

[ExtensionDiagLogs.zip](https://github.com/PowerShell/vscode-powershell/files/3880450/ExtensionDiagLogs.zip)


I'll test and check.

**Comment by JustinGrote** [comment]
@TylerLeonhardt didn't seem to fix my issue FYI.
```
Name: PowerShell Preview
Id: ms-vscode.powershell-preview
Description: (Preview) Develop PowerShell scripts in Visual Studio Code!
Version: 2019.11.1
Publisher: Microsoft


```

Updated logs using your vsix:
[PSPreviewDebugHangs.zip](https://github.com/PowerShell/vscode-powershell/files/3880481/PSPreviewDebugHangs.zip)

**Comment by TylerLeonhardt** [comment]
hmm @JustinGrote this could be specific to Pester debugging. I'll do some digging.

I do want to check to make sure @DarkLite1's issue (with regular non-Pester debugging) is fixed with that change I made.

**Comment by DarkLite1** [comment]
@TylerLeonhardt thanks for the effort but no sadly it's still not working with your updated extension. What I can see is that the code is now exectued 2 to 5 times without a problem, but after x tries of hitting `F5` it gets stuck again.

**Comment by TylerLeonhardt** [comment]
Thanks @DarkLite1 - I'll try to replicate your environment to see if I can repro.

**Comment by TylerLeonhardt** [comment]
@SeeminglyScience has a fix out for this. @SeeminglyScience if you wanna provide a test vsix for these folks, feel free to upload one.

**Comment by JustinGrote** [comment]
@TylerLeonhardt I dumped the artifacts from the build: https://dev.azure.com/powershell/PowerShellEditorServices/_build/results?buildId=39793 into my extensions module folder, and @SeeminglyScience's fix so far seems to be working for me. I ran it thru about 10-15 times and looking good so far. I'll stress test it tomorrow during development.

**Comment by SydneyhSmith** [comment]
Closing as the PR to fix this issue has been merged: https://github.com/PowerShell/PowerShellEditorServices/pull/1117
