### ISSUE TITLE
Can't edit watch variables when paused in debugging

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2396]
Issue Description
=====

When paused in the debugger:
![Capture](https://user-images.githubusercontent.com/15258962/71630062-e3d9d400-2bb5-11ea-8c8d-0a93612f96ac.gif)

This works fine with the stable extension, probably something to do with the backend rewrite.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.42.0-insider|
| PowerShell Extension Version | 2019.12.1 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.7|
|azure-pipelines|ms-azure-devops|1.157.4|
|better-align|wwm|1.1.6|
|better-comments|aaron-bond|2.0.5|
|better-powershell-syntax-highlighting|justin-grote|0.0.2|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|gc-excelviewer|GrapeCity|2.1.32|
|gistfs|vsls-contrib|0.0.38|
|git-graph|mhutchie|1.20.0|
|gitlens|eamodio|10.2.0|
|indent-rainbow|oderwat|7.4.0|
|markdown-all-in-one|yzhang|2.6.1|
|powershell-preview|ms-vscode|2019.12.1-CI.41180|
|remote-containers|ms-vscode-remote|0.96.0|
|remote-ssh-edit-nightly|ms-vscode-remote|2019.12.34080|
|remote-ssh-nightly|ms-vscode-remote|2019.12.34080|
|remote-wsl|ms-vscode-remote|0.42.0|
|team|ms-vsts|1.161.0|
|todo-tree|Gruntfuggly|0.0.162|
|vscode-icons|vscode-icons-team|9.7.0|
|vscode-peacock|johnpapa|3.2.0|
|vscode-sort-json|richie5um2|1.18.0|
|vscode-zipexplorer|slevesque|0.3.1|

**Comment by SeeminglyScience** [comment]
@JustinGrote If you change them, then press enter in the integrated console, do they update?

**Comment by SydneyhSmith** [comment]
@JustinGrote thanks for reporting this...I am having a bit of trouble reproducing this...are you using a Debug configuration?

**Comment by JustinGrote** [comment]
I've noticed it happens after extended debugging sometimes but not right
away. Let me see if I can get a better capture with detailed PSES logs.

**Comment by rjmholt** [comment]
I wonder if this is related to https://github.com/PowerShell/vscode-powershell/issues/2364

**Comment by JustinGrote** [comment]
@rjmholt @TylerLeonhardt  Just confirming this is definitely still an active issue, I'll see it after doing complicated debugging, start/stopping debug etc. after 3-5 minutes or so, however I haven't been able to nail down a root cause.

I'll turn on Debug logging and see if I can catch it in the act and submit the logs.

**Comment by rjmholt** [comment]
Sorry, this was closed by accident in the PR I just merged. It *may* be fixed by that, but needs to be manually tested.

**Comment by JustinGrote** [comment]
@rjmholt  thanks! I'll grab a CI build VSIX and give it a shot, this has been happening a lot to me during long interactive sessions.

**Comment by JustinGrote** [comment]
Just an update that this still happens to me all the time and I haven't been able to take the time to capture a full output or make it consistently reproducible.

It generally happens when I have this type of workflow:

1. Set a breakpoint
1. Start Powershell Interactive Session
1. Run a script or command and hit said breakpoint
1. **Stop the debug** rather than continue (I think the problem is in some cleanup somewhere here)
1. Start Interactive Session Again
1. Hit breakpoint but now I can't edit or change the watch variables, and they don't update
