### ISSUE TITLE
Running the contributed command: 'PowerShell.ShowSessionMenu' failed.

### ISSUE THREAD

**Issue by jithinvijayan** [PowerShell/vscode-powershell#2895]
Issue Description
=====

I recently installed vscode and the powershell extension. I am since seeing the error "Running the contributed command: 'PowerShell.ShowSessionMenu' failed." whenever vscode starts up. As a result, while the powershell terminal works fine, none of the powershell extension features in the editor works (like command completion, displaying switches, etc).

Similar to issue#[2822](https://github.com/PowerShell/vscode-powershell/issues/2822
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5088160/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5088161/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/5088162/vscode-powershell.log)

), however I don't have PS core installed.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.48.0|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.17763.1007|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.1007|
|BuildVersion|10.0.17763.1007|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|3.4.3|
|powershell|ms-vscode|2020.6.0|
|python|ms-python|2020.8.101144|
|shellcheck|timonwong|0.9.0|
|vscode-icons|vscode-icons-team|10.2.0|

**Comment by SydneyhSmith** [comment]
Thanks @jithinvijayan looks like the same issue as https://github.com/PowerShell/vscode-powershell/issues/2719 this fix is released in our latest[ PowerShell Preview extension ](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) release...could you please give that a try and see if you are still hitting this issue

**Comment by jithinvijayan** [comment]
Thanks @SydneyhSmith, I uninstalled the PowerShell extension, reloaded vscode, then installed PowerShell Preview extension. Still seeing the same issue.

**Comment by TylerLeonhardt** [comment]
Sorry @jithinvijayan, that fix will be in the _next_ release. Our bad on that. We hope to get a new version out sometime next week or so.

**Comment by jithinvijayan** [comment]
Session logs after using PowerShell preview extension:
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5093189/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5093190/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/5093191/vscode-powershell.log)

**Comment by jithinvijayan** [comment]
Looks like the issue was to do with the executionpolicy. I am running Win 10 1809, and the execution policy for currentuser was Restricted. After changing that to RemoteSigned, I am not seeing that issue anymore. Uninstalled the preview extension and installed the powershell extension, and its all good. So, looks like the executionpolicy being set to restricted to currentuser was the issue. That should be the default for all Win 10 client systems though, so could be a pre-requisite that needs to be clarified perhaps?

**Comment by jithinvijayan** [comment]
Thanks team,

**Comment by noeltupas** [comment]
I'm still seeing this issue even after setting currentuser to unrestricted.

**Comment by corbob** [comment]
> I'm still seeing this issue even after setting currentuser to unrestricted.

@noeltupas when you run `Get-ExecutionPolicy` what do you have returned? The Execution Policy is evaluated in order: Local Machine, Current User, Process, User Policy, Machine Policy. If the Process or Policies have a different setting, you will end up with those settings. To find out which policy is being applied you can run `Get-ExecutionPolicy -List` and the topmost setting that is not Undefined will be the one that's applied.

**Comment by noeltupas** [comment]
CurrentUser and LocalMachine are set to RemoteSigned, MachinePolicy UserPolicy and Process are set to Undefined

**Comment by noeltupas** [comment]
Anyone else have useful guidance on this?

**Comment by gilgame** [comment]
I've run into this before, but the session menu can't be opened until the powershell extension is loaded. Which it won't do until I open a powershell file in the editor. So if I left some other file type open when I closed my workspace or folder last, vscode doesn't start back up with the extension loaded. The solution in my case, is to just open a ps1 file from the explorer.

**Comment by seraphim72** [comment]
Running into this exact same issue. Local Machine set to RemoteSigned. All others set to undefined.

**Comment by adrianvaneeden** [comment]
> Running into this exact same issue. Local Machine set to RemoteSigned. All others set to undefined.

Same.  I'm running PowerShell 7 though.  Not sure if this would make a difference?

**Comment by damien381** [comment]
Following this

**Comment by corbob** [comment]
Someone that's still experiencing this and it's not the execution policy should probably open a new issue. Op closed this after finding the solution to their issue. Make sure to gather logs and submit them to assist with diagnosing the issue.
