### ISSUE TITLE
VS Code Powershell debugger hanging - PS 7 with Powershell extension

### ISSUE THREAD

**Issue by bkarlow-optimo** [PowerShell/vscode-powershell#3415]
Issue Description
=====

I am experiencing a problem with... VSCode debugger with Powershell integrated console set to Powershell Core version 7.1.3.  The debugger launches, finds the first breakpoint in the entry point PS1 script file, executes to the first breakpoint - all good.  

Immediately upon stepping over the breakpoint (F10), debugger hangs, terminal is non-responsive.  

This MAY be related to https://github.com/PowerShell/vscode-powershell/issues/3410 , but unclear.

This is reproduceable. 

VS Code settings:

{
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
            "versionName": "PowerShell 7"
        }
    ],
    "powershell.powerShellDefaultVersion": "PowerShell 7",
    "terminal.integrated.automationShell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
    "terminal.external.windowsExec": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
    "terminal.integrated.automationShell.osx": "",
    "terminal.integrated.automationShell.linux": "",
    "debug.javascript.autoAttachFilter": "smart",
    "vs-kubernetes": {
        "vscode-kubernetes.kubectl-path.windows": "C:\\Users\\genericuser\\.vs-kubernetes\\tools\\kubectl\\kubectl.exe",
        "vscode-kubernetes.minikube-path.windows": "C:\\Users\\genericuser\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe",
        "vscode-kubernetes.helm-path.windows": "C:\\Users\\genericuser\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe"
    },
    "mssql.connections": [
        {
            "server": "{{put-server-name-here}}",
            "database": "{{put-database-name-here}}",
            "user": "{{put-username-here}}",
            "password": "{{put-password-here}}"
        }
    ],
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell",
            "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "PowerShell 7": {
            "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
            "args": []
        }
    }
}

Attached Logs
=====

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6658738/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6658739/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/6658740/vscode-powershell.log)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19043 |
| VSCode | 1.57.0|
| PowerShell Extension Version | 2021.5.1 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.3|
|PSEdition|Core|
|GitCommitId|7.1.3|
|OS|Microsoft Windows 10.0.19043|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.3|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|armview|bencoleman|0.4.5|
|azure-account|ms-vscode|0.9.8|
|azure-pipelines|ms-azure-devops|1.188.1|
|azurecli|ms-vscode|0.5.0|
|azurerm-vscode-tools|msazurermtools|0.15.1|
|debugger-for-chrome|msjsdiag|4.12.12|
|markdown-all-in-one|yzhang|3.4.0|
|mssql|ms-mssql|1.10.1|
|npm-intellisense|christian-kohler|1.3.1|
|powershell|ms-vscode|2021.5.1|
|remote-containers|ms-vscode-remote|0.183.0|
|remote-wsl|ms-vscode-remote|0.56.5|
|rest-client|humao|0.24.5|
|vscode-aks-tools|ms-kubernetes-tools|0.0.8|
|vscode-apimanagement|ms-azuretools|1.0.2|
|vscode-azureappservice|ms-azuretools|0.22.0|
|vscode-azurefunctions|ms-azuretools|1.4.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestorage|ms-azuretools|0.12.1|
|vscode-azurevirtualmachines|ms-azuretools|0.4.0|
|vscode-bicep|ms-azuretools|0.4.63|
|vscode-commons|redhat|0.0.6|
|vscode-cosmosdb|ms-azuretools|0.16.0|
|vscode-docker|ms-azuretools|1.13.0|
|vscode-dotnet-runtime|ms-dotnettools|1.1.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.3|
|vscode-markdownlint|DavidAnson|0.42.1|
|vscode-node-azure-pack|ms-vscode|0.2.1|
|vscode-npm-script|eg2|0.3.22|
|vscode-yaml|redhat|0.19.2|

**Comment by strickdd** [comment]
I'm having a very similar issue, but the debugger never hits the first breakpoint and I'm using PS 5.1. It shows the toolbar (screenshot below), but never hits the breakpoint and the terminal hangs - can't scroll or type.

Debug Toolbar
![image](https://user-images.githubusercontent.com/4924102/122978850-efe6c200-d364-11eb-9797-33830570f7a3.png)

**Simple Script**
```
function Get-SomeVal {
    # Breakpoint on this line
    'Some Val' | Write-Output
}

Get-SomeVal
```

**Logs**
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6696595/EditorServices.log)
[PowerShellEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6696596/PowerShellEditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6696597/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/6696598/vscode-powershell.log)

**Code Version**
```
PS:\>code -v
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```

**Extensions**
```
PS:\>code --list-extensions --show-versions
eamodio.gitlens@11.5.1
mhutchie.git-graph@1.30.0
ms-azuretools.vscode-docker@1.14.0
ms-dotnettools.csharp@1.23.12
ms-vscode-remote.remote-containers@0.183.0
ms-vscode-remote.remote-wsl@0.56.5
ms-vscode.powershell@2021.6.1
ms-vscode.vs-keybindings@0.2.1
shd101wyy.markdown-preview-enhanced@0.5.21
slevesque.vscode-autohotkey@0.2.2
```

**Editor Services Version**
```
PS:\>$psEditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
2      4      4      0       
```

**PSVersion Table**
```
PS:\>$PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.18362.1474
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1474
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by strickdd** [comment]
Not sure if it matters, but highlighting code and pressing F8 runs that section of code without issue.

**Comment by andschwa** [comment]
Hey, just an FYI we are actively working on https://github.com/PowerShell/PowerShellEditorServices/issues/1295 which re-wires the debugger. Hence we are prioritizing that rather than fixing issues with the existing implementation. We intend to have that in the next preview, and then we will see if this problem goes away 😄

**Comment by bkarlow-optimo** [comment]
@strickdd - 
Thanks for the feedback.  I'm glad I'm not the only one experiencing similar issues.  

@andschwa - 
Thank you for the feedback.  Understood regarding focus on new implementation of the debugger, and that is great news.  I still think it important to raise these issues so others are aware they are not alone.  

Any target release date for the new debugger?  I read through the referenced thread and saw a mentioned target date of EOY 2020, which obviously is no longer accurate.

**Comment by andschwa** [comment]
The whole year of 2020 was...a mess, for everyone (also I was not yet a maintainer here). We are planning to get it into the next release, hopefully end of this month, potentially next month, but not much later than that!

**Comment by bkarlow-optimo** [comment]
@andschwa - Thank you for the update.  I suppose I can work around this issue for now.  Regards.

**Comment by peetrike** [comment]
The problem might be connected to PSReadline v2.2.0-Beta3 (reported in https://github.com/PowerShell/PSReadLine/issues/2616)

**Comment by strickdd** [comment]
I know I wasn't in the list, but in case it helps... here are my available PSReadline modules.
![image](https://user-images.githubusercontent.com/4924102/123459240-02a30600-d5b4-11eb-829a-c357985eef93.png)

**Comment by bkarlow-optimo** [comment]
I am only on version 2.1.0.  See below:

PS C:\> Get-Module PSReadline -ListAvailable

    Directory: C:\program files\powershell\7\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}        

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.0.0      beta2      PSReadline                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}

**Comment by hemingsent** [comment]
> If that is the case, could @peetrike and @bkarlow-optimo try ensuring you only have PSReadLine 2.1.0 on the machine?
> 
> [#3393 (comment)](https://github.com/PowerShell/vscode-powershell/issues/3393#issuecomment-854095942)
> 
> I will try to prioritize this: [PowerShell/PowerShellEditorServices#1493](https://github.com/PowerShell/PowerShellEditorServices/issues/1493)

This was indeed my issue. I removed the PSReadline v2.2.0-Beta3 and now it is working properly.

**Comment by thomglow** [comment]
Uninstalling PSReadline v2.2.0-Beta3 fixed my issue with the debugger hanging also.

**Comment by hemingsent** [comment]
> > If that is the case, could @peetrike and @bkarlow-optimo try ensuring you only have PSReadLine 2.1.0 on the machine?
> > [#3393 (comment)](https://github.com/PowerShell/vscode-powershell/issues/3393#issuecomment-854095942)
> > I will try to prioritize this: [PowerShell/PowerShellEditorServices#1493](https://github.com/PowerShell/PowerShellEditorServices/issues/1493)
> 
> This was indeed my issue. I removed the PSReadline v2.2.0-Beta3 and now it is working properly.

I spoke too soon. I removed it and it worked for a while, now it is back. With only 2.1 installed. I will keep testing and see what may have caused the issue to reappear.

**Comment by andschwa** [comment]
I'm dropping a new Preview of the release this week that will only use the bundled version of PSReadLine, and so should avoid this issue entirely!

**Comment by andschwa** [comment]
@thomglow Can you try the 2021.7.0-preview version ("PowerShell Preview") on the marketplace, install PSReadLine v2.2.0-beta3 on your machine, and verify that this issue is fixed? The preview extension has logic now that only loads the bundled PSReadLine 😁

**Comment by hemingsent** [comment]
@andschwa  I did test mine without and beta of PSReadLine and it still hangs for me. I will get some more information here shortly and edit this post.

**Comment by andschwa** [comment]
Oops, actually I mean @hemingsent, whose issues _did_ have to do with PSReadLine beta3. I think your issue is different.

**Comment by peetrike** [comment]
> @thomglow Can you try the 2021.7.0-preview version ("PowerShell Preview") on the marketplace, install PSReadLine v2.2.0-beta3 on your machine, and verify that this issue is fixed?

the 2021.7.0-preview works with PSReadLine v2.2.0-beta3.  Debugger starts and works normally

**Comment by thomglow** [comment]
With the 2021.7.0-preview of the PowerShell extension in VSCode and
PSReadLine v2.2.0-beta3, my issues of running code in VSCode and having it
hang, have been resolved. Thank you.

**Comment by andschwa** [comment]
Yay, thank you!

**Comment by andschwa** [comment]
I'm going to leave this issue open as @bkarlow-optimo original reported issue is, to my knowledge, unrelated to the PSReadLine beta3 incompatibility issue.

**Comment by strickdd** [comment]
Just installed 2021.7.0-preview with PSReadLine v2.2.0-beta3 and tested. Debugger hangs for me still. The debug toolbar comes up, but the breakpoint is never hit. I'm using PS 5.1. The terminal locks up and has to be killed/restarted to interact with it again.

It looks like PSReadline 2.1.0 was loaded initially so I removed that and manually loaded PSReadline 2.2.0. 

After manually loading 2.2.0, I run and get an error in the PowerShell Editor Services log (below). The weird thing is that it mentions "untitled:Untitled-2", but the file I'm trying to debug is "GroupMembershipRecurseWithCreds.ps1".

I'm happy to run any additional tests or provide additional details.

```
[Warn  - 9:48:21 AM] Microsoft.PowerShell.EditorServices.Services.WorkspaceService: Failed to get file for fileUri: 'untitled:Untitled-2' | 
[Error - 9:48:21 AM] Microsoft.PowerShell.EditorServices.Services.PowerShellContextService: Execution of the following command(s) completed with errors:

    Microsoft.PowerShell.Utility\Set-PSBreakpoint -Command 

 | 
[Warn  - 9:48:21 AM] Microsoft.PowerShell.EditorServices.Services.PowerShellContextService: Runtime exception occurred while executing command | 
```

**Additional Screenshots/Info**
![image](https://user-images.githubusercontent.com/4924102/126649338-0f4588e7-d3a3-4b76-818d-e0071e9f4baf.png)

![image](https://user-images.githubusercontent.com/4924102/126649503-93cfdf0e-de91-4706-9715-fdcbab234874.png)

```
PS C:\> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.18362.1474
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1474
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment]
Sounds like your issue @strickdd is also (unfortunately) not the PSReadLine issue.

**Comment by UselessGuru** [comment]
I am the co-developer of [https://github.com/Minerx117/NemosMiner/tree/testing](https://github.com/Minerx117/NemosMiner/tree/testing) and I've got slightly different problem with the debugger which might be related.

Executing
```
Add-Type -AssemblyName System.Windows.Forms
$Form = New-Object System.Windows.Forms.Form
```
breaks the debugger - the breakpoint gets hit, but the relevant code will not get highlighted.

Sample code to reproduce the problem:

```
Function MyFunction { 
    Param(
        [Parameter(Mandatory = $false)]
        [String]$text
    )

    Write-Host $Text
    Start-Sleep -Seconds 1
}

MyFunction "Before Add-Type & Form"

Add-Type -AssemblyName System.Windows.Forms
$Form = New-Object System.Windows.Forms.Form

MyFunction "After Add-Type & Form"
```

1. Add a breakpoint to line 8 (Start-Sleep -Seconds 1)
2. Start debugging.
3. The first call to MyFunction prints 'Before Add-Type & Form' and the debugger highlights line 8.
4. Continue the script with 'F5'
5. The second call to MyFunction prints 'After Add-Type & Form'. **The debugger does not highlight anything.**

Working combo: 
pwsh 7.0.2-preview5 or older
powershell extension 2021.2.2 or older

Upgrading pwsh to -preview7 or later breaks the debugger

upgrading the powershell extension to a newer version (incl. preview 2021.7.0) does not help.

Any ideas?

**Comment by andschwa** [comment]
Yes, we seem to have a number of issues right now around the use of `System.Windows.Forms`. I need to (or someone else, if you're willing) debug through PowerShell Editor Services to see if we messed up any async calls. Most likely we need to ensure that `.ConfigureAwait(false)` is used on _every_ call, otherwise the threads get mixed up since `Forms` brings in its own threads too. A process dump of your issue would be quite helpful!

**Comment by UselessGuru** [comment]
>  I need to (or someone else, if you're willing) debug through PowerShell Editor Services 

I am please to help - can you give exact instructions.
I know how to debug Powershell. However I do not (yet) understant 'PowerShell Editor Services'. Any links to prepare myself?

**Comment by AfanasievAA** [comment]
I have same issue. 
```
[void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
$test = New-Object "System.Windows.Forms.Form"
Write-Host "OK"
```
After breakpoint gets hit, pressing F10 reproduces a problem (debugger does not highlight anything and hungs). If you then hit F11 - script continues (writes "OK" to host) but debugger hungs anyway.

**Comment by andschwa** [comment]
Your script has been quite useful, I spent yesterday debugging! I've got things a little more stable (you can now exit the debugger even after it "hangs" at that breakpoint, which didn't seem to be working at first).

It's perhaps a little painful to get this debugged, you end up with three concurrent debugging sessions. Before getting to that point, if you're interested, you can get setup just debugging PSES and the extension following [these instructions](https://github.com/PowerShell/vscode-powershell/blob/master/docs/development.md).

**Comment by rjmholt** [comment]
See also: https://github.com/PowerShell/vscode-powershell/issues/2352

**Comment by andschwa** [comment]
@UselessGuru @AfanasievAA  (and anyone else with issues debugging a PowerShell script which uses an object from `Systems.Windows.Forms`), could you test the dev build uploaded in the linked comment and let me know if the issue is resolved? Thank you! https://github.com/PowerShell/vscode-powershell/issues/3394#issuecomment-895604756

@bkarlow-optimo is your issue the same as theirs, or separate?

**Comment by AfanasievAA** [comment]
I've quick tested it. It works! No more debugger fails. Used Visual Studio Code 1.60.0 insider (x64) with your extension.

**Comment by UselessGuru** [comment]
> could you test the dev build uploaded in the linked comment

I've quick tested it. It works! VSC 1.59 & PWSH 7.2-Preview8

**Comment by andschwa** [comment]
@bkarlow-optimo and @strickdd I'm not certain your issues were the same root cause, but would you test the dev build posted in https://github.com/PowerShell/vscode-powershell/issues/3394#issuecomment-895604756 so I know?

**Comment by andschwa** [comment]
> @bkarlow-optimo and @strickdd I'm not certain your issues were the same root cause, but would you test the dev build posted in [#3394 (comment)](https://github.com/PowerShell/vscode-powershell/issues/3394#issuecomment-895604756) so I know?

Since my best guess is that this was related to the threading issues within PSES and OmniSharp, and since those are now fixed and merged, I'm going to mark this issue as resolved. Please wait for the next update to the extension to roll out (no later than Monday) and see if this has been fully resolved for you. If not, since this thread got long and covered several problems, please open a new issue.
