### ISSUE TITLE
Annoying animation when pasting long string into PowerShell

### ISSUE THREAD

**Issue by kkshinkai** [PowerShell/vscode-powershell#3756]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I've had this problem since I started using PowerShell. When I try to paste a long string (usually a path) into PowerShell, it always plays a typewriter animation and I have to wait until it's done.

![vscode-pwsh-example](https://user-images.githubusercontent.com/38599375/148656809-d4640688-d75a-4851-9dd1-f97e8d057b20.gif)

I am not confident that the problem is with this plugin, but PowerShell works fine after I disabling it, so I guess it's not a VSCode or terminal issue. The `Terminal.app` that comes with macOS is also fine.

Is there any way we could remove this animation? This is almost the only reason I don't use PowerShell.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 21.1.0 Darwin Kernel Ve…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Just open

**Comment by SydneyhSmith** [comment]
Thanks so much for your issue @kkshinkai , it appears that this is actually a performance issue where the underlying calls to PSReadline delay the pasting in a way that makes it appear as an animation... I will mark this as a performance issue

**Comment by SydneyhSmith** [comment]
It would also be great if you could try our preview extension as some of the performance improvements released there may solve this issue

**Comment by josefwegner** [comment]
Hi,

I have the same issue on my Raspberry Pi 400 running Debian Bullseye ARM64. I also tried the preview extension, but sadly, pasting stuff is still as slow as the release extension.

**PowerShell Version**
```
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
** VSCode Version**
```
> code --version
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
arm64
```

**Extension Version**
```
ms-vscode.powershell-preview
```

**Comment by JustinGrote** [comment]
I don't have this issue when pasting on Windows, perhaps it is MacOS specific? I believe the vscode terminal implementations use different VTYs between MacOS and Windows. Does this happen in a regular terminal too e.g. bash?

https://user-images.githubusercontent.com/15258962/150815580-2718b9a1-03da-4e79-87b7-1bc1fb7beb63.mp4

**Comment by andschwa** [comment]
Hi there, we just released [v2022.4.0-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.4.0-preview)! Could you please try [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) and verify this is fixed? It seemed to be in my testing, so marking as resolved, but please let me know if it's still occurs (or if new bugs show up)!

**Comment by andschwa** [comment]
This was an ancient bug that was _really annoying_ and I am super happy to see it fixed.

**Comment by josefwegner** [comment]
Thank you, it is much, much better.
But on my Raspberry Pi 400 (Debian Bullseye AMD64), the last 5 or 6 chars are still appearing with a delay. This is regardless how long the pasted string is. The first n-6 chars appear instantaneously, the last 6 chars char by char. I will try to make a screen capture later today.

**Comment by josefwegner** [comment]
Sorry for the shakiness. But I could not capture the slowness using a screen recorder. I hope you can still see my issue:
https://www.youtube.com/watch?v=8gTtWyA0iqE

**Comment by andschwa** [comment]
Woah, that's _so_ interesting. At this point, we are quite literally only calling .NET's `Console.ReadKey()` API. I'm curious, does this "last 6 character" issue occur in a regular `pwsh` console (in and/or out of VS Code, and definitely with PSReadLine)?

**Comment by josefwegner** [comment]
No, it does not happen in a regular `pwsh` console inside and outside of VS Code. PSReadLine is definitely activated:
$PROFILE:
```
...
Set-PSReadLineOption -EditMode Vi
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
...
```
