### ISSUE TITLE
Run Selection with F8 defaults cursor to Terminal

### ISSUE THREAD

**Issue by brettmillerb** [PowerShell/vscode-powershell#544]
### System Details

- Operating system name and version: 10.0.10586
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.63
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.63
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Not sure if it's by design but running selection using `F8` defaults the cursor location to the integrated terminal meaning you have to move back to the editor.

Tested on a colleagues VSCode and his cursor remains in the editor when using `F8` to run selection. Unsure which version he is using specifically unfortunately.

ISE also remains in the editor.

**Comment by daviwil** [comment]
Whoops, forgot about this issue when I filed #556.  At any rate, this has been fixed now, will be shipped in a day or so!

**Comment by JakobGSvendsen** [comment]
this issue is still there on multiple install I have made within the last month?

Can I disable it?

**Comment by brettmillerb** [comment]
You can add the setting to your profile @jakobGSvendsen. 

`"powershell.integratedConsole.focusConsoleOnExecute": false`

I spoke to @daviwil about it and the setting couldn't be implemented by default so it's now a user setting.

**Comment by daviwil** [comment]
Hey Jakob!  Brett is correct, we had to leave "focus console on execute" as the default behavior due to accessibility requirements.  If you add the setting that Brett pasted to your User Settings, you'll get the behavior that you want.
